### ISSUE TITLE
[Mac- Incognito Mode] Profile Page incomplete

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#1]
While clicking on Profile Page , noting is been shown. 

https://user-images.githubusercontent.com/86723241/123963236-fc58c380-d9d1-11eb-9a05-465ba47be64d.mp4

<img width="1431" alt="profile page incomplete" src="https://user-images.githubusercontent.com/86723241/123963262-0084e100-d9d2-11eb-8aca-7b27ad9dfe2e.png">

**Comment by deepaksursa** [comment]
![image](https://user-images.githubusercontent.com/55537459/124108793-34214300-da86-11eb-9e28-8378bfaeb411.png)

**Comment by sursaone** [comment]
Thanks. This has been fixed, please check with new account registration or by updating the current profile. cc @iambijay12
