### ISSUE TITLE
The Teacher profile is accessible even without login.

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#10]
Steps:
Go to the course page before login.
Click on the Teacher's name under the class

Actual: 

The page redirects to the Teacher page without any information in it , also the user is not asked to Login . 

Screencast:

https://user-images.githubusercontent.com/86723241/123991826-c542dc00-d9ea-11eb-8dde-092552ab9247.mp4

**Comment by sursaone** [comment]
I think it is fine to be public
