### ISSUE TITLE
Course is not seen in Dashboard even after its published. 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#100]
I got the mail for the confirmation  of course being published. But it's not reflected in. Dashboard. 

https://uat.vurilo.com/

https://user-images.githubusercontent.com/86723241/133884708-7a0ad22b-b73b-48d9-a685-64492630ba0d.mp4

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/144563611-93701811-472f-4fd4-b21a-aae2966e9d1e.mp4
