### ISSUE TITLE
Unable to delete Course Thumbnail

### ISSUE THREAD

**Issue by deepaksursa** [vurilo/support#105]
Mode : Prod/UAT 
**Reference** 
![image](https://user-images.githubusercontent.com/55537459/133929528-045da784-19de-4c27-9372-bbaaf56bb420.png)

![image](https://user-images.githubusercontent.com/55537459/133929495-192b878b-4391-4eb1-8f39-b686fe2f903a.png)

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/144362016-333a9f8e-3748-47c5-806d-cf345576343a.mp4
