### ISSUE TITLE
[Password recovery] - Eye icon missing in Password recovery window. 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#109]
![Vurilo_Eye icon missing_Reset password](https://user-images.githubusercontent.com/86723241/134149575-780c3566-8886-4496-8138-081f4082c739.png)

**Comment by saurabhchaulagai** [comment]
![image](https://user-images.githubusercontent.com/70097566/144226515-dd021cf0-0759-4db2-ac06-f4e5e4d18568.png)
