### ISSUE TITLE
[Profile Edit} - Drag and drop is not working 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#110]
https://user-images.githubusercontent.com/86723241/134161806-16e90bd2-7a3f-459a-a8ad-a1765d502b2d.mp4

<img width="1432" alt="drag n drop" src="https://user-images.githubusercontent.com/86723241/134161999-f4fe8766-3779-41ab-8d87-d241b44abaec.png">

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/144225849-78e5ebdd-611c-4cb0-b9cf-c0aecd56bf3e.mp4
