### ISSUE TITLE
[Home page ] - Browse is not functioning as a list of categories, rather it is acting as search. 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#117]
https://user-images.githubusercontent.com/86723241/134660086-25a0096b-bb17-452a-8445-c9c1b2add754.mp4

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/144225409-591884e9-bb2e-4943-bdf2-e28953d84ba9.mp4
