### ISSUE TITLE
[Settings (Edit Profile)] unable to upload profile picture or remove profile picture

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#121]
### Test to Reproduce
go to settings page
go to edit profile
observe the functionality of uploading or removing profile picture

### Expected results
User should able to remove previous profile picture and allow to upload new one.

### Actual results
User is unable to remove previous profile picture.

### my point of view
1. If the business logic is not to give to change profile picture then admin must verified the picture, and give verify tag to profile 
picture and disable removing function.
2. If the business logic is not mandatory to verify profile picture then application should allow to remove previous profile picture and also allow to upload new profile picture.
.
### Screenshot/Video

https://user-images.githubusercontent.com/19512522/140735138-a690a1e1-8caf-4a60-8cfb-993c2750cbdf.mp4

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/144563065-329f10fa-e8c7-4bea-a0f2-472086c6d667.mp4
