### ISSUE TITLE
[Tech] By default course title field is active. When user try to click outside the input field increase form size

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#128]
### Test to Reproduce
go to teach.
click on create new course
click on outside the active input field

### Expected results
By default course title field should active. When user try to click outside the input field should show appropriate message within same box as there is enough space to show error message.

### Actual results
By default course title field is active. When user try to click outside the input field increase the size of form and show appropriate message.

### Screenshot/Video

https://user-images.githubusercontent.com/19512522/140916636-97e5af53-7c5d-46ca-9c88-afad2cf833ec.mp4

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/145034796-b6f8f5bd-c861-4c3a-848f-b6a46f86608f.mp4
