### ISSUE TITLE
[Team] By default team name field is active. When user try to click outside the input field increase form size

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#129]
### Test to Reproduce
go to teach
click on create your team
click on outside the active input field

### Expected results
By default team name field should active. When user try to click outside the input field should show appropriate message within same box as there is enough space to show error message.

### Actual results
By default team name field is active. When user try to click outside the input field increase the size of form and show appropriate message.

### Screenshot/Video

https://user-images.githubusercontent.com/19512522/140916341-c3838510-ba97-405a-ba73-b219d915eb25.mp4

**Comment by rabijee** [comment]
#128 same issues

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/145035118-3fa6e741-9cf7-4d26-ad02-a959e9d850b7.mp4
