### ISSUE TITLE
[Course Detail Page] - Some UI been observed in Course Detail Page. 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#13]
Steps:

1. Go to the course Detail Page. 
2. Fill the data in the given fields. 
3. Observe the error message. 
4. Observe the Price value .

**Actual** 
The error message displayed is deem and also the price field shows in decimal value after entering long integer. 

**Screenshot:**

<img width="1440" alt="Course Detail Page_UI Issue" src="https://user-images.githubusercontent.com/86723241/124066509-7cc20780-da58-11eb-916d-be786698f957.png">

**Comment by sursaone** [comment]
color were fixed, must be cache issue. decimal is correct as it is
