### ISSUE TITLE
[ Profile ] User name and professional allows numeric character

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#133]
### Test to Reproduce
go to profile
Edit name and profession
Enter numeric value

### Expected results
The Application should display "Invalid username, please enter valid first/last name, profession"

### Actual results
Application is taking numeric values input as user name and profession.

### Suggestions
The username and profession should take text as input and show error while giving numeric value as input.

### Screenshot/Video
![Profile_name_and_profession_taking_numeric_values](https://user-images.githubusercontent.com/19512522/140921277-a85e79ea-0e17-4031-a22b-b96d8bb8971b.png)

https://user-images.githubusercontent.com/19512522/140921287-1deaf3b5-26d2-4d0b-9f3d-28d839a1ecbc.mp4

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/145034195-fd13da0d-a55d-4995-9042-1e554f9183cd.mp4
