### ISSUE TITLE
[Navbar] - heading alignment error

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#142]
### Test to Reproduce
1.click on become instructor navbar

### Expected results
heading of all reason should have same alignment.

### Actual results
All reason have different heading alignment.

### Screenshot/Video

https://user-images.githubusercontent.com/19512522/141274570-283e64e4-a479-476a-ac46-bf299ed005f5.mp4

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/144361767-f36135d2-2849-46fb-aeca-a2e50d09af97.mp4
