### ISSUE TITLE
[publish course]  word limit on column is not breaking the text

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#144]
### Expected results
Area of description field should auto limit column size or break the text field.

### Actual results
Area of description field is not breaking text field.

### Screenshot/videos
![word limit](https://user-images.githubusercontent.com/19512522/141278072-ce7ea736-d0d4-48b3-be64-0fd5026ca65a.png)

**Comment by saurabhchaulagai** [comment]
![image](https://user-images.githubusercontent.com/70097566/144361551-efe96e3b-7f22-468a-ba7a-4904816f77ab.png)
