### ISSUE TITLE
[Settings] - invalid input type is accepting in mobile number.

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#147]
### Test to Reproduce

click on profile icon
click on settings
enter character as a value in phone number in input field instead of integer as value

### Expected results

Application should accept integer value.
Application should display error message for invalid data type.

### Actual results

Application accepts all value (any data-types) send it to server.

### Screenshot/Video

https://user-images.githubusercontent.com/19512522/141281468-a6e1865b-d89f-4f54-8dc3-90c2132a12a5.mp4

**Comment by saurabhchaulagai** [comment]
It should only let user to input value from 0-9 


![147](https://user-images.githubusercontent.com/70097566/145032985-20b945db-f0d3-49f7-a3ee-f56bbba31980.png)
Max length should be 15
![147A](https://user-images.githubusercontent.com/70097566/145032991-48ac31a4-1874-495a-a02e-66c211e7b7cb.png)
