### ISSUE TITLE
[Course Detail Page] - Course Thumbnail says Size not available while uploading 276 kb . jpg file

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#15]
**Steps**:

Go to the course Detail Page.
Upload the thumbnail . 
256 KB , .jpg file were uploaded. 
Observe the error message.

**Actual**
Size not available error message shown.

**Screenshot**:
![flyer](https://user-images.githubusercontent.com/86723241/124069378-cb24d580-da5b-11eb-9954-6c8866c7ec43.jpeg)

https://user-images.githubusercontent.com/86723241/124069442-e5f74a00-da5b-11eb-94a6-f6ee93454ac9.mp4

https://user-images.githubusercontent.com/86723241/124069387-ceb85c80-da5b-11eb-8c7b-a4cfcca08bc7.mp4

**Comment by sursaone** [comment]
this should be fixed now.
