### ISSUE TITLE
[profile icon] Text inside profile icon

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#153]
### Expected results
Text size inside profile icon should be capital letter.

### Actual results
Text size inside profile icon is small letter.

### Screenshot/Video
![profile_text_size](https://user-images.githubusercontent.com/19512522/141286322-2fed29fc-1e0d-4c21-aa44-31deb3d61716.png)

**Comment by saurabhchaulagai** [comment]
![153](https://user-images.githubusercontent.com/70097566/145030522-52cafb42-776a-4a0f-8555-445913f1fb95.png)
