### ISSUE TITLE
[Tech] Input position change when error message display

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#154]
### Test to Reproduce

go to tech module
go draft course
go to details input field
click on input field

### Expected results
Input fields should be in same position when error message display.

### Actual results
Input fields changing its position.

### Screenshot/Video

https://user-images.githubusercontent.com/19512522/141287149-ef9f98bd-909b-4069-9342-4401a3f0611a.mp4

**Comment by saurabhchaulagai** [comment]
![154](https://user-images.githubusercontent.com/70097566/145030237-6526f2f1-e1ab-4c84-9be7-6e6d4d40f3dd.png)
