### ISSUE TITLE
[Registration Form] Form is flicking when all field display error

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#155]
### Test to Reproduce
1. click on sign Up button
1. enter invalid data

### Expected results
Form size should be fixed when error message display inside input field. Application should flick inside same form size. upper gap and bottom gap are enough to flick input field, label, logo, button.

### Actual results
Form size is flicking when error message display.

### Suggestion
Form element should flick rather than flicking form size

### Screenshot/Video

https://user-images.githubusercontent.com/19512522/141287369-59cd37b7-767b-4096-8e26-a02196d1c0ed.mp4

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/144999016-6ad7ef58-4b1e-4782-b1d7-3c6c245cf7f4.mp4
