### ISSUE TITLE
[Settings] Breadcrumb of setting page is showing page is active in Edit profile but in sidebar there is no color for active sidebar items

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#158]
### Test to Reproduce
1. click on profile icon
1. click on settings

### Expected results
1. Application should have breadcrumb in top left.
1. Application should highlight the active sidebar items.

### Actual results
1. Application shows breadcrumb for active page.
1. Application is not highlighting the items of sidebar of the page.

### Screenshot/Video
![_settings_-_sidebar_is_not_highlighted](https://user-images.githubusercontent.com/19512522/141290826-372e66b1-d0e2-4f6e-9543-897244ddd797.png)

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/144417927-b0004640-a5eb-43c4-b17e-a6759acfdd69.mp4
