### ISSUE TITLE
[Signup Page] While clicking on the eye icon many times , it highlights the Info .

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#160]
### Test to Reproduce
1. Click on the Vutilo Url 
2. Click on the Sign Up option .
3. Fill the password field and click on the eye icon many more times and observe.

### Expected result
The Application should show the password of the user when the user clicks on the eye icon and again when the user clicks on the eye icon, it should display the dots. 

### Actual results
The application highlights the [info] attached with a password when the user clicks on the eye icon many more times. 

### Screenshot/Video

https://user-images.githubusercontent.com/19512522/141292301-4056fa81-f0e7-43b9-ac1b-85961d349a0e.mp4

**Comment by Sunamika123** [comment]
It's okay, I don't think it is necessary to fix.

**Comment by saurabhchaulagai** [comment]
yes, because it is highlighting the info section.

**Comment by Rashi011** [comment]
This issue has already been resolved.

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/145770235-c138a827-a939-492e-ab54-a1bdf66318e0.mp4
