### ISSUE TITLE
[Tech] User is unable to remove selected thumbnail

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#161]
### Test to Reproduce

1. Open browser into incognito
1. Login on the Vurilo uat
1. Click on profile icon
1. Click on teach
1. Go to required course
1. Update thumbnail
Remove the existing thumbnail

### Expected results
Existing thumbnail should have been removed

### Actual results
No action is done on trying to remove thumbnail

### Screenshot/Videos

https://user-images.githubusercontent.com/19512522/141293695-26bb3e68-a89a-494f-bfd2-e39695f42755.mp4

**Comment by saurabhchaulagai** [comment]
user can't remove the error course thumbnail also.
https://user-images.githubusercontent.com/70097566/144202823-2c9d11b3-2f5f-4ddd-971d-b587b84df92c.mp4

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/144566120-d3c42dcd-a9c1-4ad3-9418-1247e086c586.mp4
