### ISSUE TITLE
[ Homepage ] Pop up showing "facebook icon", "instagram icon", "youtube icon" on hovering

### ISSUE THREAD

**Issue by rabijee** [vurilo/support#163]
### Test to Reproduce

1. Open browser into incognito
1. Login on the Vurilo uat
1. Scroll down to the bottom left. 
1. Click on the different social media icons

### Expected results

The hover effect should not display "Facebook icon", "Youtube icon", "Instagram icon"

### Actual results
The hover effect is displaying "Facebook icon", "Youtube icon", "Instagram icon".

Suggestion:
If it is business logic to show names then it would better to show for facebook icon just "facebook" and so on...........

### Screenshot/Video

https://user-images.githubusercontent.com/19512522/141428136-e3103a88-eea3-4da0-85e4-6c4d532fab50.mp4

https://user-images.githubusercontent.com/19512522/141428167-1b38d91a-b98d-49c1-84c1-e82e2841d90c.mp4

**Comment by Sunamika123** [comment]
why not hover??
