### ISSUE TITLE
[Course Detail] - The price field shows different behaviour that accepts one alphabet also.

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#17]
**Steps**:

Go to the course Detail Page.
Fill the values in the field. 
Enter the  integer value in Price field. 

**Actual**
when we type alphabet "e" it accepts , but it does not accept other alphabet. 

**Screenshot**:

<img width="1440" alt="format mismatch" src="https://user-images.githubusercontent.com/86723241/124091340-74c49080-da75-11eb-87fb-46994916f128.png">

https://user-images.githubusercontent.com/86723241/124091355-78581780-da75-11eb-8294-bb31664471a8.mp4

**Comment by sursaone** [comment]
e is number so it takes that.
