### ISSUE TITLE
[Porfile Page] Image is not loading 

### ISSUE THREAD

**Issue by deepaksursa** [vurilo/support#18]
![image](https://user-images.githubusercontent.com/55537459/124109915-5f586200-da87-11eb-9dea-29a28b90431b.png)

**Comment by sursaone** [comment]
No actually there should be upload section at the top of the form

**Comment by drasticdpk** [comment]
![image](https://user-images.githubusercontent.com/25297859/124222278-27056200-db21-11eb-883a-7f3d6ecd0abc.png)

**Comment by sursaone** [comment]
@deepaksursa what error are you getting?

Regarding the attachment at the bottom lets have it, so we can add more on profiles.
