### ISSUE TITLE
[course][discussion]-cannot delete the question

### ISSUE THREAD

**Issue by saurabhchaulagai** [vurilo/support#181]
### Pre-condition
1. open incognito mode in google chrome.
2. login to uat.vurilo.com.
3. click on other's course.
4. click on show reply

4. delete the question you have posted in the discussion section.

### Expected result
It should delete the posted question.

### Actual result
The question is not deleted.

### Video
https://user-images.githubusercontent.com/70097566/142999011-260a6b86-edfe-4a81-932a-c3bc3d32de12.mp4

**Comment by phuyalrn22** [comment]
this issue only exists on old comments.
