### ISSUE TITLE
[login][reset password]-the previous link shows the text field

### ISSUE THREAD

**Issue by saurabhchaulagai** [vurilo/support#186]
### Pre-condition
1. open uat.vurilo.com in google incognito mode.
2. click on the login button from the top right corner.
3. click on reset password.
4. fill the email field with the login email.
5. Again repeat the process from step 2.
6. click on the 1st link from the mail.

### expected result
It should only show the error message.

### Actual result
It is showing the error message along with the text field.

### Video

https://user-images.githubusercontent.com/70097566/143992311-417de97c-47c2-4e3b-ad74-80caa5e72a99.mp4

**Comment by Sunamika123** [comment]
It is okay. After session expired, it shows an error message.
