### ISSUE TITLE
Add popup on Landing page

### ISSUE THREAD

**Issue by deepaksursa** [vurilo/support#194]
Let's add popup on landing page where we can add our sales promotion banner. 

Action : 
1. Popup should auto disappear after X seconds of time ( for now please set 5 sec )
2. User should able to close the popup ( by clicking outside the popup or X icon ) 
3. Add below image 
4. Redirection Link : https://www.vurilo.com/live 

cc  @subhamsursa @Rashi011  

![Vurilo_ promotion_post](https://user-images.githubusercontent.com/55537459/150525564-39215677-9770-422b-9f89-7f65d639bdfd.png)

**Comment by phuyalrn22** [comment]
https://user-images.githubusercontent.com/92909608/150672583-a116d0a2-9773-42ec-9e7e-cf92189d5a88.mp4

**Comment by phuyalrn22** [comment]
@deepaksursa need to redirect on /live or /meet?

**Comment by deepaksursa** [comment]
@phuyalrn22 for now please set 5 sec.

**Comment by deepaksursa** [comment]
![image](https://user-images.githubusercontent.com/55537459/150731986-b70d9dd0-b73f-4955-9245-90a305724bed.png)

**Comment by deepaksursa** [comment]
> @deepaksursa need to redirect on /live or /meet?

it   has to go /meet

**Comment by deepaksursa** [comment]
@phuyalrn22 let us know once it is on **Ready For QA** status
