### ISSUE TITLE
Hyperlink issue at  course details.

### ISSUE THREAD

**Issue by deepaksursa** [vurilo/support#196]
Reference : 
![image](https://user-images.githubusercontent.com/55537459/151538662-f0ef7822-bd9a-4c91-a5d7-5fb4db45daad.png)

**Comment by phuyalrn22** [comment]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/92909608/158354583-379e71a1-e59f-4367-9aa5-713f970c7f86.png">

**Comment by Rashi011** [comment]
We will be working on markdown from the beginning
