### ISSUE TITLE
404 error occured while clicking on Become Instructor

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#2]
Steps : 
Go to the  COurse page . 
Scroll down 
CLick on Become Instructor  
Observe 

Actual Result : 
While clicking on Become Instructor - it' shows 404 Error

Screenshot:

https://user-images.githubusercontent.com/86723241/123964370-0fb85e80-d9d3-11eb-8a99-3c0460ff469f.mp4

**Comment by sursaone** [comment]
https://app.vurilo.com/teach/start
