### ISSUE TITLE
[Course Detail ] - After clicking the Publish button, it shows an error message.

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#20]
**Steps**:

Go to the course Detail Page.
Fill the data in the given fields.
Submit it.
Then click on Publish from the Dashboard

**Actual**
The error message comes while publishing it. 

**Screenshot**:

https://user-images.githubusercontent.com/86723241/124112323-e7d80200-da89-11eb-8901-7952cc978bc0.mp4

**Comment by iambijay12** [comment]
@iambijay12
