### ISSUE TITLE
Recording verification

### ISSUE THREAD

**Issue by ST-Saurabh** [vurilo/support#200]
Removing the recordings from the zoom after verifying it in Vurilo till 2023/03/07

Due date: 2023/03/08

**Comment by Karki5suman310** [comment]
@all recording verification from Name classes until today

**Comment by ST-Saurabh** [comment]
https://github.com/vurilo/support/issues/207

**Comment by Karki5suman310** [comment]
Removing the recordings from the zoom after verifying it in Vurilo till 2023/03/10

**Comment by ST-Saurabh** [comment]
still ielts recording verification has not been done

**Comment by Karki5suman310** [comment]
@ recording verification finished from Name classes until today
