### ISSUE TITLE
Verifying Zoom Recording

### ISSUE THREAD

**Issue by VuriloSabina** [vurilo/support#207]
SEE PREPARATION 2079 (ENGLISH & NEPALI MEDIUM)

**Comment by ST-Saurabh** [comment]
@VuriloSabina ma'am what is the status of the task???

**Comment by VuriloSabina** [comment]
SEE Class recordings verification has been completed.

**Comment by ST-Saurabh** [comment]
@VuriloSabina ma'am the recording verification is incomplete.
![image](https://user-images.githubusercontent.com/109574221/224277094-00851d85-8087-45f0-b7cd-35d94c0781a5.png)
