### ISSUE TITLE
[Course Detail] - The successful submission message displays in the corner of the page which is not visible if the user is in top page.

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#21]
Steps:

Go to the course Detail Page.
Fill the data in the given fields.
Click the Submit  button.
Observe the success message display placement. 

Actual
The success message is displaying in the bottom right corner in a small font, for the  13 inch screen it's likely to miss the  message and user gets confuse if it was submitted or not. 

Screenshot:

https://user-images.githubusercontent.com/86723241/124112599-2cfc3400-da8a-11eb-9765-f4b312069859.mp4

**Comment by sursaone** [comment]
@SangeetaRaya Can you please share the screenshot when you are on top :-p ?

**Comment by SangeetaRaya** [comment]
well its good to have feature , as the success message is small and pops at the corner, so there might be a chance to miss out, since in my first  submission I was looking in the image and didn't notice the message posed up  so I clicked the submit button again. 
Or we can  make the submit button disable after the success message comes , 
just giving the suggestion to increase the usability of the product.
