### ISSUE TITLE
Call to the 150 student 

### ISSUE THREAD

**Issue by kumarichandra** [vurilo/support#214]
call to the 100 students around 6pm to8 pm

maximum students received my call 

also they are taking the booking class

**Comment by kumarichandra** [comment]
my this task is complete follow up to the students

28feb to march 9

**Comment by ST-Saurabh** [comment]
@kumarichandra ma'am can you provide the details of the students called?

**Comment by kumarichandra** [comment]
https://docs.google.com/spreadsheets/d/1hSWIH5tQ4DoUwRbzW6JMqyGj4TSjqZaYwLfycnOFIV8/edit#gid=1493137262
I worked this sheet.
