### ISSUE TITLE
Enroll and send the mail two students

### ISSUE THREAD

**Issue by kumarichandra** [vurilo/support#215]
Asmi Adhikari and Nikee Adhikari
send the maill also

**Comment by ST-Saurabh** [comment]
@kumarichandra ma'am please provide the email address and the mail sent evidences here.

**Comment by kumarichandra** [comment]
asmiadhikari040@gmail.com
![image](https://user-images.githubusercontent.com/127376232/226526611-dc144aa6-066a-4cfc-a1de-98e780d67f5f.png)
aaryanp801@gmail.com
![image](https://user-images.githubusercontent.com/127376232/226526803-e8fe4dd3-9a46-43cb-979b-3519133b51ff.png)
