### ISSUE TITLE
[Setting] - The change email feature error message is not matching the context. 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#24]
**Steps:**

Go to setting.
Click on Change email. 
enter invalid email but valid password
Observe the error message displayed

**Actual Result:**
The error message reds like :"The password is invalid or the user does not have a password":
Better message would, the email and the password does not match. Please retry.

**Screencast:**

https://user-images.githubusercontent.com/86723241/124121882-2921df00-da95-11eb-883d-303319e14a2b.mp4

<img width="1126" alt="change email error message " src="https://user-images.githubusercontent.com/86723241/124121873-2626ee80-da95-11eb-93a0-40792e7ecf81.png">

**Comment by sursaone** [comment]
The message is from google firebase and is correct per their system.
