### ISSUE TITLE
online payment details 

### ISSUE THREAD

**Issue by Karki5suman310** [vurilo/support#241]
Online payment details by E Sewa mention sheet

**Comment by ST-Saurabh** [comment]
@Karki5suman310 sir please add all the details here too to take reference in the future
]

**Comment by Karki5suman310** [comment]
Payment final link 
https://docs.google.com/spreadsheets/d/1hSWIH5tQ4DoUwRbzW6JMqyGj4TSjqZaYwLfycnOFIV8/edit#gid=2072513198
