### ISSUE TITLE
student has been enrolled from viber and bulk sent class link dated march-4-2023 

### ISSUE THREAD

**Issue by kumarichandra** [vurilo/support#242]
student has been enrolled of viber 
Message will send by Suma sir

**Comment by Karki5suman310** [comment]
Today 66 students enrolled until 6 pm. date march 4
https://docs.google.com/spreadsheets/d/1hSWIH5tQ4DoUwRbzW6JMqyGj4TSjqZaYwLfycnOFIV8/edit#gid=1466370944

**Comment by Karki5suman310** [comment]
Class link sent ncell number 
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Phone | Network | Status | Dispatched On
-- | -- | -- | --
9819660500 | Ncell | delivered | Mar 14 2023, 16:55
9811856001 | Ncell | accepted | Mar 14 2023, 16:55
9813524600 | Ncell | delivered | Mar 14 2023, 16:55
9804674750 | Ncell | accepted | Mar 14 2023, 16:55
9814980846 | Ncell | delivered | Mar 14 2023, 16:55
9822889098 | Ncell | delivered | Mar 14 2023, 16:55
9826726274 | Ncell | delivered | Mar 14 2023, 16:55
9811487838 | Ncell | delivered | Mar 14 2023, 16:55
9826822459 | Ncell | accepted | Mar 14 2023, 16:55
9616694716 | SmartTel | accepted | Mar 14 2023, 16:55
9824391676 | Ncell | delivered | Mar 14 2023, 16:55
9810954964 | Ncell | delivered | Mar 14 2023, 16:55
9808951924 | Ncell | accepted | Mar 14 2023, 16:55
9813044304 | Ncell | delivered | Mar 14 2023, 16:55
9810292442 | Ncell | delivered | Mar 14 2023, 16:55
9819619376 | Ncell | delivered | Mar 14 2023, 16:55
9810545819 | Ncell | delivered | Mar 14 2023, 16:55
9828085284 | Ncell | delivered | Mar 14 2023, 16:55
9818120852 | Ncell | delivered | Mar 14 2023, 16:55
9827401468 | Ncell | accepted | Mar 14 2023, 16:55
9814513400 | Ncell | delivered | Mar 14 2023, 16:55
9813239798 | Ncell | delivered | Mar 14 2023, 16:55
9803089106 | Ncell | delivered | Mar 14 2023, 16:55
9824967402 | Ncell | delivered | Mar 14 2023, 16:55
9826870380 | Ncell | delivered | Mar 14 2023, 16:55
9813708807 | Ncell | delivered | Mar 14 2023, 16:55
9829471202 | Ncell | accepted | Mar 14 2023, 16:55
9825676700 | Ncell | delivered | Mar 14 2023, 16:55
9811217736 | Ncell | delivered | Mar 14 2023, 16:55
9813410151 | Ncell | accepted | Mar 14 2023, 16:55
9813576343 | Ncell | delivered | Mar 14 2023, 16:55
9815872411 | Ncell | delivered | Mar 14 2023, 16:55
9828736057 | Ncell | delivered | Mar 14 2023, 16:55
9811248038 | Ncell | delivered | Mar 14 2023, 16:55
9811459576 | Ncell | accepted | Mar 14 2023, 16:55
9818732448 | Ncell | delivered | Mar 14 2023, 16:55
  |   |   |  


</body>
</html>

NTc Number status 
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Phone | Network | Status | Dispatched On
-- | -- | -- | --
9848582888 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9841414813 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9865095974 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9843444231 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9867159010 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9863614356 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9745652846 | NT CDMA | accepted | Mar 14 2023, 17:02
9844827742 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9840422610 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9864396406 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9742567014 | NT CDMA | accepted | Mar 14 2023, 17:02
9745520972 | NT CDMA | accepted | Mar 14 2023, 17:02
9863760395 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9863330048 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9849158119 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9840765704 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9844031048 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9852670458 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9860023112 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9861743654 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9869085023 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9864867555 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9748345170 | NT CDMA | accepted | Mar 14 2023, 17:02
9842630828 | Nepal Telecom | accepted | Mar 14 2023, 17:02
9845300886 | Nepal Telecom | accepted | Mar 14 2023, 17:02


</body>
</html>
