### ISSUE TITLE
Call to Shanti Bashyal(9841508488) March15

### ISSUE THREAD

**Issue by kumarichandra** [vurilo/support#246]
9841508488
this number send by Govinda call not received that time 
today call received but he had been paid Physicaly
We have't receive the Shanti Bashyal Received.
She is not enroll and not receive the massage
@SumanKarki Sir What can we do this situation.

**Comment by Karki5suman310** [comment]
@chandra tamang ***@***.***> mam, Please check voucher and
enrolled and supported

**Comment by kumarichandra** [comment]
paid by her father so enrolled in booking class and send the message 
enrolled through this number 9745652545
