### ISSUE TITLE
[COurse Detail ] - The price field is taking default value after refreshing.

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#26]
**Steps:**
Go to the Teach 
Go to the dashboard 
Choose one course.
Click on Detail page
Observe the price field.

**Actual Result:**

Price field is taking it's own default value , even though the user have entered different price quote. 

**Screencast:**

https://user-images.githubusercontent.com/86723241/124160765-546bf480-dabc-11eb-9fdb-34e90f52cc07.mp4

**Comment by sursaone** [comment]
@SangeetaRaya I can't replicate this. It must be due to backend max size, since now UI has validation you can't add more than 50000
