### ISSUE TITLE
payment students verified and enroll new number 

### ISSUE THREAD

**Issue by Karki5suman310** [vurilo/support#267]
Please enrolled and call 
Suvi Adhikari for pre booking class 
Everest Collage ,biraltnagar
 enroll number 9819360189
Panchali, Biratnagar-12
Usle vurilo bata 9pm ma 

9842957836 bata paisa send gareko xa hai

**Comment by Chandra1120** [comment]
Sure




*Regards,Chandra Kumari Tamang | Customer Support RepresentativeVurilo
Nepal Pvt. Ltd.+977-9801230314*

**Comment by kumarichandra** [comment]
Call to the students and conform
suviadhikari777@gmail.com
log in through this email and class will be take
[Suvi.pdf](https://github.com/vurilo/support/files/11014380/Suvi.pdf)

**Comment by kumarichandra** [comment]
[Suvi.pdf](https://github.com/vurilo/support/files/11014456/Suvi.pdf)
Completed
