### ISSUE TITLE
Enrolled  in pre booking class(Kabita Jaisi)

### ISSUE THREAD

**Issue by kumarichandra** [vurilo/support#277]
9745997094
Kabita Jaisi
gairekabita64@gmail.com
need to call after 5pm

**Comment by kumarichandra** [comment]
![image](https://user-images.githubusercontent.com/127376232/226806254-ce054526-1471-49e6-916a-346675495e4c.png)

**Comment by Karki5suman310** [comment]
next time including details send number also.
