### ISSUE TITLE
[teams] - Create team- The phone number field does not have validation for 0 and space . 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#28]
Steps:

Click on User profile and click on Teams.
Create a team 
Fill the values in the pop up box
Enter phone number 
Observe the error message under phone number text box.

Actual
The phone number field accepts 11 integer number, along with 977- but when we keep space and 0 in between it accepts that too. 

Screenshot:

https://user-images.githubusercontent.com/86723241/124229082-c845e580-db2c-11eb-99e9-23c930b3f1a7.mp4

<img width="1316" alt="phone number validation" src="https://user-images.githubusercontent.com/86723241/124229100-d09e2080-db2c-11eb-8365-28a5c1e53d32.png">

**Comment by sursaone** [comment]
this looks validated, please check once
