### ISSUE TITLE
[Team] - Newly created team can't be deleted.

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#29]
Steps:

Click on User profile and click on Teams.
Create a team
Fill the values in the pop up box
See the newly created teams . 
Delete the Teams

Actual
The system does not have the delete option, If a teacher wants to delete the team then we don't have option or is it a part of business that once created team can't be deleted?

Screenshot:

<img width="1438" alt="Delete team option not availabel" src="https://user-images.githubusercontent.com/86723241/124229695-b9abfe00-db2d-11eb-901c-bea58deab85d.png">

**Comment by sursaone** [comment]
Team can't be deleted, this has been developed intentionally. We can add in future if needed.
