### ISSUE TITLE
[Course] - The created course  does not show up in order. 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#31]
Steps:
Click on user profile and click on Teams.
Create a team
Observe the message displayed at top.

Actual :
The ordering of the created course does not follow either the Date or the alphabetical order.

Screenshot:

<img width="1415" alt="ordering of created course" src="https://user-images.githubusercontent.com/86723241/124235186-ab151500-db34-11eb-839b-27896d3ab6cc.png">

**Comment by iambijay12** [comment]
@iambijay12
