### ISSUE TITLE
[Teams] - It's good to have validation on the fields like email, Name .

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#33]
Steps: 

1. Go to User Profile 
2. Click on Teams
3. Click on Create New team button
4. fill the junk values in the fields like Name and email and observe.

Actual : 
email is taking any value like abc@xy.com
and name is also taking integer , special character etc. 

Screenshot: 
<img width="1427" alt="email validation_teams " src="https://user-images.githubusercontent.com/86723241/124269223-58e6ea80-db5a-11eb-86b0-2c5b9315cbc4.png">

https://user-images.githubusercontent.com/86723241/124269240-5c7a7180-db5a-11eb-9876-31c24e38fae9.mp4

**Comment by sursaone** [comment]
we won't restrict name to be validated, email is valid per rule
