### ISSUE TITLE
{Download our app] The error message for  downloading the app is not visible.

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#4]
**Steps** : 
Go to the home page. 
Scroll down 
Click on Download our app 
click submit without entering the email. 
Observe the error message 
 
**Actual result**
while clicking on App store option the error message showing is not readable. 

![error message not clear](https://user-images.githubusercontent.com/86723241/123965410-24e1bd00-d9d4-11eb-87fb-3e80c63773c7.png)

**Comment by sursaone** [comment]
This has been fixed, must be cache issue.
