### ISSUE TITLE
[Social Media] - There is an inconsistency in presence of Social Media 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#42]
Some pages have just Facebook, Youtube and Instagram. 
In some pages we have Twitter, facebook, Youtube, Github,  Instagram. 

Suggestion: It's better to have consistency through out the page. 
However Linkedin is missing. 

<img width="1214" alt="social media" src="https://user-images.githubusercontent.com/86723241/124309178-0cb39e80-db8a-11eb-9dc1-6024e6e30d76.png">
<img width="1435" alt="Social Media_Terms of  service" src="https://user-images.githubusercontent.com/86723241/124309187-11785280-db8a-11eb-8e8b-40bd0377d9f2.png">

**Comment by sursaone** [comment]
This is invalid, in the profile page it is user's social media, in footer its vurilo's social link
