### ISSUE TITLE
[Log out] - Logout is not working as expected. 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#43]
Logging out does not take the user in logout page. 

The current page still exist.

**Screencast:**

https://user-images.githubusercontent.com/86723241/124309491-821f6f00-db8a-11eb-8ce5-c99c5ea5fdf2.mp4

**Comment by sursaone** [comment]
Yes because this is same as login or without login. only difference is you won't see the edit icon if not logged
