### ISSUE TITLE
[Lesson] - The edit me text box still shows Edit me after clicking on it. 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#54]
When we click on the text box the place holder should be vanished. 

https://user-images.githubusercontent.com/86723241/125200850-5c7e1e00-e28c-11eb-824c-2c04af8fa387.mp4

**Comment by sursaone** [comment]
It is value to be updates so it will be like that, you need to change and save it.

**Comment by iambijay12** [comment]
Edit Text is coming from the backend it self, so i can't be done auto remove while user click in input field.

**Comment by sursaone** [comment]
ok
