### ISSUE TITLE
[Section] - Course upload video doesn't have file size limit but taking too long to upload.

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#55]
The video is taking too long time upload. Also it showed an error message  but didn't mention the reason to failure. 

<img width="1440" alt="section upload_Error" src="https://user-images.githubusercontent.com/86723241/125201253-f6929600-e28d-11eb-97ba-5dc35db98c00.png">

https://user-images.githubusercontent.com/86723241/125201303-3eb1b880-e28e-11eb-946a-f5eee78ce170.mp4

**Comment by iambijay12** [comment]
There is no error on uploading video. i have uploaded the 396 MB
