### ISSUE TITLE
[Creating a Team] - While creating a course , how can we create team . 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#56]
Steps : 
Under course Detail page. 
After entering all the value and selecting Who can access this course as Only my Team member. 
How can we create team , 

Also the system shows success message even without selecting the team  with mandatory field. 

https://user-images.githubusercontent.com/86723241/125202313-ca2d4880-e292-11eb-8d0f-0148b9c67ecf.mp4

<img width="1437" alt="select team" src="https://user-images.githubusercontent.com/86723241/125202331-e03b0900-e292-11eb-9ede-fa7ca48c3e64.png">

**Comment by sursaone** [comment]
@iambijay12 it is because we are setting default team on backend, please make that nullable and if empty it should mean the default team and anyone can access.
