### ISSUE TITLE
[Course Detail Page] - UI Issue - The size of textbook are inconsistence.

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#57]
The size of the text box is not equal . 

<img width="1411" alt="inconsistency in text box" src="https://user-images.githubusercontent.com/86723241/125227143-0e036a80-e2f2-11eb-9c6c-e57823bfa992.png">

**Comment by sursaone** [comment]
It is fine, course title is 200 characters while other are short. cc @iambijay12
