### ISSUE TITLE
[Lesson] - UI Suggestion - Incomplete content has been observed. 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#59]
After the course successfully added, Teacher is able to see the added section and lesson page. But the content in each Lesson appears to be incomplete. 

Suggestion:
Can we have no text limit or do some truncates that gives a meaning also and look also improves. 

<img width="1431" alt="UI_Incomplete content" src="https://user-images.githubusercontent.com/86723241/125231360-5757b800-e2fa-11eb-8468-6033a1f1ecd0.png">

**Comment by iambijay12** [comment]
text max size = 100
