### ISSUE TITLE
[Issues shown in interface]

### ISSUE THREAD

**Issue by Rashi011** [vurilo/support#70]
1) Interface (Home page) would look much better if it showed an image or slider that represents Vurilo.
2) only after logging in or signing up showing or displaying the list of courses could have been better.
3) would it be better if we placed social media (Facebook, Instagram, Google) and the app store's logo at the footer? 
4) there are two logos, can we just keep one? 
5) In the light theme, the copyright 2021 Vurilo is visible, but in the dark mode, it is barely visible. Maybe we could change the color of the text "Vurilo"
6) while clicking on status, we land on a new page. Would it be better if we get directed to the home page if we click the logo?  
7) error message pop up- grammar and language check.  (image no.1)
8) after typing the password if the eye icon to show the password is kept, it would be better. 
9) sign up-  password must be longer than 8 characters, including numbers, special characters, and uppercase letters. (image no.2)
10) sign up -  Remove the word "new" and just keep "enter your password". 

https://drive.google.com/drive/u/1/folders/1afY-LIijalK2ypzMDUtgcmTc5E3Ctl1v
This is the link to the video and images regarding issues experienced in the app.

**Comment by iambijay12** [comment]
2 . Regarding issues no 2, To view course user doesn't required to login.
5. Fixed
6. Regarding issues no 6. There is Vurilo Tab
7. Fixed
8. Fixed
10. Fixed
