### ISSUE TITLE
Unable to see course description 

### ISSUE THREAD

**Issue by RaunakMaskay** [vurilo/support#79]
Course Description text and background both is in white colour. 

Path: https://app.vurilo.com/teach/17ac5f67-8fbd-4685-8330-d63594cd7a76/edit 

![image](https://user-images.githubusercontent.com/4321550/127624587-fb883b68-da0c-4185-b638-7e02c739b2e0.png)

**Comment by sursaone** [comment]
@iambijay12 please check this as well 
![image](https://user-images.githubusercontent.com/37689201/127776464-e82069ee-50ea-441e-b3a8-8c05a646103e.png)

**Comment by RaunakMaskay** [comment]
Dark Mode Firefox
