### ISSUE TITLE
[Status] - The status page is visible to all user even without Login In.

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#8]
Step : 
Go to the right  corner below the page. 
Click on Status . 
Status opens in next page.

Actual : 
I am able to view the status even without login. 
Do we have the control on accessing status by all. 

Screencast: 

https://user-images.githubusercontent.com/86723241/123990665-b14aaa80-d9e9-11eb-8793-2de14998a41b.mp4

<img width="1368" alt="status page" src="https://user-images.githubusercontent.com/86723241/123990721-be679980-d9e9-11eb-8c6b-ad81de98dd8a.png">

**Comment by sursaone** [comment]
typo fixed.

but this will be public
