### ISSUE TITLE
Unable to see video description

### ISSUE THREAD

**Issue by RaunakMaskay** [vurilo/support#80]
![image](https://user-images.githubusercontent.com/4321550/127625746-cce454c1-a467-484f-b758-f7d2a79ef09c.png)
Path: https://app.vurilo.com/teach/17ac5f67-8fbd-4685-8330-d63594cd7a76/lessons 
Text and background both white here as well.

**Comment by sursaone** [comment]
@iambijay12 are you able to replicate this? I am not able to see on mac chrome

cc @RaunakMaskay

**Comment by RaunakMaskay** [comment]
Dark Mode Firefox

**Comment by sursaone** [comment]
Thanks able to replicate on FF and it is fixed now
