### ISSUE TITLE
Current Password should be loaded but asked everytime

### ISSUE THREAD

**Issue by RaunakMaskay** [vurilo/support#83]
![image](https://user-images.githubusercontent.com/4321550/127626738-df2ef0f8-d98c-4769-8d95-01b7063054a0.png)
Path: https://app.vurilo.com/settings/password

**Comment by sursaone** [comment]
It shouldn't be loaded as we don't store the password on our side.

User either need to use the browser's password auto fill or use third party tools to auto fill like this 

![image](https://user-images.githubusercontent.com/37689201/127776683-438aa4dd-db11-4c8b-a39f-76761a9fa275.png)

**Comment by RaunakMaskay** [comment]
Current password is loaded automatically in mine

**Comment by sursaone** [comment]
@RaunakMaskay It must be due to browser's password auto fill?

**Comment by RaunakMaskay** [comment]
Can you check in Fireforx for this as well?

**Comment by sursaone** [comment]
@RaunakMaskay i tested on FireFox and found that it when password is saved it is auto filled, this is default behavior of firefox. 

We have followed the https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete this feature to support auto complete and based on this firefox automatically completes the field if valid autocomplete field is implemented.

I think this is good to have. If user don't save the password using the firefox then it won't fill automatically.
