### ISSUE TITLE
User does not know whether there is a video or not

### ISSUE THREAD

**Issue by RaunakMaskay** [vurilo/support#85]
![image](https://user-images.githubusercontent.com/4321550/127627537-bbb7304b-4d22-40c5-8205-c6558d52e817.png)

User ought to know whether there is a video, maybe a auto-thumbnail of first frame

**Comment by sursaone** [comment]
yes auto thumbnail should be there once video is uploaded but until it is uploaded, the UI will ask the upload the video.
