### ISSUE TITLE
Unable to delete all videos

### ISSUE THREAD

**Issue by RaunakMaskay** [vurilo/support#90]
The last video cannot be deleted
https://uat.api.vurilo.com/api/lesson/08f07200-d803-4ed1-9c44-539a402f4625?courseId=17ac5f67-8fbd-4685-8330-d63594cd7a76
![image](https://user-images.githubusercontent.com/4321550/127635883-58d21ac7-09d6-4f4f-86cd-73a761edfd16.png)

**Comment by iambijay12** [comment]
It is working fine
