### ISSUE TITLE
Course is created successfully even without selecting the mandatory field. 

### ISSUE THREAD

**Issue by SangeetaRaya** [vurilo/support#99]
Course is created successfully even without selecting the mandatory field. 

https://user-images.githubusercontent.com/86723241/133882591-933de69a-b5ba-4c5a-8067-e6e501aaa595.mp4

**Comment by saurabhchaulagai** [comment]
https://user-images.githubusercontent.com/70097566/144564816-3d9b0511-4d36-4080-b270-4e17da2fefbc.mp4
